config/routes.rb
Rails.application.routes.draw do
  resources :marketing_pages
  resources :events do
  	collection do
      post :update_event
  	end
  end
  resources :communities do
  	collection do
  		post :find_community
      get :find_phone
      get :find_email
      get :find_short_name
      get :dashboard
      post :update_crop
      post :universal_search
      get :featured_community
      get :count_for_home_and_community
  	end
  end
	get 'page_not_found', to: 'communities#page_not_found', as: :page_not_found
	post "communities/new_community" => "communities#new_community"
  resources :community_facilities
  root to: "admin/login#new"	
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 #get 'community_offers#new'
 get 'contacts/index'

 get 'contacts/show'
 #get 'community_offer', to: :new, controller: 'community_offers'
 # resources :contacts
 resources :home_for_sales do
  collection do
    post 'sales_force_callback'
    get :featured_home
    get :sorted_homes
  end
 end
 
 resources :home_layouts
 resources :form_submissions
 resources :community_offers
 resources :community_categories
 resources :pdf_info_packs do
    collection do
      put :featured_pdf_info_pack
      get :featured_pack
    end
  end
namespace :admin do 
 resources :login do
  post 'static_login', on: :collection
  get 'logout', on: :collection
 end
end  

 
end

app/models/activity.rb
class Activity < ApplicationRecord
  mount_uploader :image, ActivityImageUploader
  belongs_to :community, inverse_of: :activities
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/community.rb
class Community < ApplicationRecord
  include AlgoliaSearch

  has_and_belongs_to_many :community_categories,dependent: :destroy
  has_one :pdf_info_pack
  has_many :community_facilities, inverse_of: :community, dependent: :destroy
  has_one :community_offer
  # belongs_to :home_for_sale
  has_many :activities, inverse_of: :community,dependent: :destroy
  has_many :why_live_heres, inverse_of: :community,dependent: :destroy
  has_many :facebook_links, inverse_of: :community,dependent: :destroy
  has_many :community_images, inverse_of: :community, dependent: :destroy
  accepts_nested_attributes_for :community_facilities, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :activities, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :why_live_heres, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :facebook_links, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :community_images, reject_if: :all_blank, allow_destroy: true
  validates_presence_of :slug
  validates_presence_of :short_name
  validates_uniqueness_of :short_name, :slug
  # validates :community_icon, presence: true
  # validates :community_logo, presence: true
  # validates :salesperson_image, presence: true
  # validates :featured_image, presence: true
  after_create :update_slug
  before_update :assign_slug
  mount_uploader :community_logo, ImageUploader
  mount_uploader :community_icon, ImageUploader
  mount_uploader :community_infopack, AttachmentUploader
  mount_uploader :salesperson_image, ImageUploader
  mount_uploader :featured_image, ImageUploader   
  mount_uploader :masterplan_pdf, MasterplanUploader
  mount_uploader :masterplan_image, ImageUploader 
  mount_uploader :legend_image, ImageUploader 
  enum state_name: [
    "Queensland", "New South Wales", "Victoria"
  ]

  geocoded_by :street_address, :latitude => :latitude, :longitude => :longitude
  after_validation :geocode

  algoliasearch do
    # all attributes will be sent
  end
  
	def slug
    self.short_name.downcase.gsub(" ", "-")  
  end
  
  def to_param
    slug
  end
  private

  def assign_slug
    self.slug = self.short_name.downcase.gsub(" ", "-")
  end

  def update_slug
    update_attributes slug: assign_slug
  end
  
end

app/models/community_category.rb
class CommunityCategory < ApplicationRecord
	has_and_belongs_to_many :communities
	mount_uploader :image, ImageUploader
end

app/models/community_facility.rb
class CommunityFacility < ApplicationRecord
  mount_uploader :image, FacilityImageUploader
  belongs_to :community, inverse_of: :community_facilities
end

app/models/community_image.rb
class CommunityImage < ApplicationRecord
	mount_uploader :community_images, WhyLiveHereImageUploader
  belongs_to :community, inverse_of: :community_images
  validates :community_images, presence: true
end

app/models/community_offer.rb
class CommunityOffer < ApplicationRecord
	validates :title, presence: true
	#validates :image, presence: true
	mount_uploader :image, ImageUploader
	has_many :communities
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
  include AlgoliaSearch
  belongs_to :community, optional: true
	algoliasearch do
    # all attributes will be sent
  end
end

app/models/facebook_link.rb
class FacebookLink < ApplicationRecord
  belongs_to :community, inverse_of: :facebook_links
end

app/models/form_submission.rb
class FormSubmission < ApplicationRecord
end

app/models/home_for_sale.rb
class HomeForSale < ApplicationRecord
	include AlgoliaSearch
  
  belongs_to :community, optional: true
	algoliasearch do
    # all attributes will be sent
  end

  def upload_on_cloudinary
  	new_images = []
  	self.images.each do |img|
  	  url = Cloudinary::Uploader.upload(img)
  	  new_images << url["secure_url"]
  	end
  	self.images = new_images
  	self.save!
  end
end

app/models/home_layout.rb
class HomeLayout < ApplicationRecord
	mount_uploader :floorplan_image, LayoutUploader
	mount_uploader :floorplan_pdf, FloorplanUploader
	validates :feature_title1, presence: true
	validates :feature_title2, presence: true
	validates :feature_title3, presence: true
	validates :feature_title4, presence: true
	validates :description1, presence: true
	validates :description2, presence: true
	validates :description3, presence: true
	validates :description4, presence: true
end

app/models/marketing_page.rb
class MarketingPage < ApplicationRecord
end

app/models/pdf_info_pack.rb
class PdfInfoPack < ApplicationRecord
  has_many :communities
  mount_uploader :info_pdf, PdfinfoUploader
  validates_size_of :info_pdf, maximum: 20.megabytes, message: "should be less than 20 MB"
end

app/models/why_live_here.rb
class WhyLiveHere < ApplicationRecord
  #validates :image, presence: true
  mount_uploader :image, WhyLiveHereImageUploader
  belongs_to :community, inverse_of: :why_live_heres
end

app/controllers/form_submissions_controller.rb
class FormSubmissionsController < ApplicationController
	def index
    @form_submissions = FormSubmission.all
  end

  def show
  	@form_submission = FormSubmission.find(params[:id])
    if @form_submission.present?
    	respond_to do |format|
	    	format.html
	      format.json { render json: @form_submission }
	  	end
    else
	  	redirect_to :page_not_found
	  end	
  end

  def new
    @form_submission = FormSubmission.new
  end


  def edit
  	@form_submission = FormSubmission.find(params[:id])
  end

  def create
    @form_submission = FormSubmission.new(form_submission_params)
	  respond_to do |format|
	    if @form_submission.save
				format.json { redirect_to form_submissions_path, status: :created}
				flash[:info] = 'Submission Created'
				format.html {redirect_to form_submissions_path}
			else
				format.json { render json: @form_submission.errors, status: :unprocessable_entity}
				format.html { render 'new'}
			end
	end
  end	

  def update
    @form_submission = FormSubmission.find(params[:id])
	  if @form_submission.update(form_submission_params)
	  	flash[:info] = 'Submission Updated'
	    redirect_to form_submissions_path
	  else
	    render 'edit'
	  end
  end

  def destroy
    @form_submission = FormSubmission.find(params[:id])
	  @form_submission.destroy
	 	flash[:info] = 'Submission deleted'
	  redirect_to form_submissions_path
  end


  private
    def form_submission_params
      params.require(:form_submission).permit(:first_name, :last_name, :phone, :email, :planning, :additional_info, :attachment, :source_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/form_submissions_helper.rb
module FormSubmissionsHelper
end

app/helpers/home_layouts_helper.rb
module HomeLayoutsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/form_submissions/_form.html.erb
<div class="all-wrapper menu-side">
  <div class="layout-w">
    <div class="menu-mobile menu-activated-on-click color-scheme-dark">
    </div>
    <div class="content-w">
      <ul class="breadcrumb">
        <% if @form_submission.new_record? %>
          <li class="breadcrumb-item">
            <a href="#">Home</a>
          </li>
          <li class="breadcrumb-item">
            <a href="/form_submissions">Form submissions</a>
          </li>
          <li class="breadcrumb-item">
            <a href="#">New form submission</a>
          </li>
        <% else %>
          <li class="breadcrumb-item">
            <a href="#">Home</a>
          </li>
          <li class="breadcrumb-item">
            <a href="/form_submissions">Form submissions</a>
          </li>
          <li class="breadcrumb-item">
            <a href="#">Edit form submission</a>
          </li>
        <% end %>  
      </ul>
      <div class="content-i">
        <div class="content-box"><div class="row">
<div class="col-lg-12">
<div class="element-wrapper">
  <div class="element-box">
    <% if @form_submission.new_record? %>
      <div class="form-group">
        <p class="addnewcomm">New form submission</p>
      </div> 
    <% else %>
      <div class="form-group">
        <p class="addnewcomm">Edit form submission</p>
      </div>
    <% end %>    
      <div class="form-group">
        <label for="" class="enter-a-community-na">First Name*</label>
        <%= f.text_field :first_name, class: "form-control which-part-will-be-c", placeholder: "Eg: Brewer", required: true %>
      </div>
      <div class="form-group">
        <label for="" class="enter-a-community-na">Last Name*</label>
        <%= f.text_field :last_name, class: "form-control which-part-will-be-c", placeholder: "Eg: Brewer", required: true %>
      </div>
      <div class="form-group">
        <label for="" class="enter-a-community-na">Email*</label>
        <%= f.text_field :email, class: "form-control which-part-will-be-c", placeholder: "Eg: gateway@gmail.com", required: true %>
      </div>
      <div class="form-group">
        <label for="" class="enter-a-community-na">When are you planning to buy home*</label>
        <%= f.text_field :planning, class: "form-control which-part-will-be-c", placeholder: "Eg: 8month", required: true %>
      </div>
      <div class="form-group">
        <label for="" class="enter-a-community-na">Additional Info*</label>
        <%= f.text_field :additional_info, class: "form-control which-part-will-be-c", placeholder: "Eg: Brewer", required: true %>
      </div>
      <div class="form-group">
        <label for="" class="enter-a-community-na">Attachment*</label>
        <%= f.text_field :attachment, class: "form-control which-part-will-be-c", placeholder: "Eg: file_name.docs", required: true %>
      </div>
      <div class="form-group">
        <label for="" class="enter-a-community-na">Show source url*</label>
        <%= f.text_field :source_url, class: "form-control which-part-will-be-c", placeholder: "Eg:", required: true %>
      </div>
      
      <% if @form_submission.new_record? %>
        <div class="form-buttons-w">
          <%= f.submit :"SAVE AND PUBLISH", class: "mr-2 mb-2 btn btn-success draft1",name: "visibility" %>
          <%= f.submit :"SAVE AS DRAFT", class: "mr-2 mb-2 btn btn-default draft" %>
        </div>
      <% else %>
        <%#= f.submit :"UPDATE", class: "button-background" %>
        <%= f.submit :"UPDATE", class: "mr-2 mb-2 btn btn-succ update" %>
        <%= link_to "DELETE", form_submission_path(form_submission.id) , method: :delete, class: "mr-2 mb-2 btn btn-dan update1"%>
      <% end %>   
  </div>
</div>
</div>
</div>
        </div>
      </div>
    </div>
  </div>
</div>
<script src="//widget.cloudinary.com/global/all.js" type="text/javascript"></script>  
<script type="text/javascript">  
  $('#floorplanimage').cloudinary_upload_widget(
    { cloud_name: 'gateway-lifestyle', upload_preset: 'ecaya9l1', 
      cropping: 'server', folder: 'user_photos',
      cropping_show_dimensions: "true",
      theme: "white",
      gravity: "custom",
      moderation: "webpurify" },
    function(error, result) 
    { 
      if(error == null){
        $("#uploaded_logo1").html('<img src="'+result[0]["thumbnail_url"]+'">')
      } 
    });
</script>
<script> 
  $( document ).ready(function() {
    $("#new_home_layout").validate({
      errorElement: 'span',
      errorClass: 'desc',
      rules: {
        "home_layout[name]": {
         required: true
        },
        "home_layout[feature_title1]": {
         required: true,
        },
        "home_layout[feature_title2]": {
         required: true
        },
        "home_layout[feature_title3]": {
         required: true
        },
        "home_layout[feature_title4]": {
         required: true
        }
      }    
    }); 
  });
</script>

app/views/form_submissions/edit.html.erb
<div class="container">
  <% if @form_submission.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@form_submission.errors.count, "error") %> prohibited
        this formsubmission from being saved:
      </h2>
      <ul>
        <% @form_submission.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_for @form_submission do |f| %>
    <%= render partial: 'form', locals: {form_submission: @form_submission, f: f}%>
  <% end %>
</div>



 

app/views/form_submissions/index.html.erb
<div class="all-wrapper menu-side">
  <div class="layout-w">
    <div class="content-w">
      <ul class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="#">Home</a>
        </li>
        <li class="breadcrumb-item">
          <a href="/form_submissions/new">Form submissions</a>
        </li>
      </ul>
      <div class="content-i">
        <div class="content-box">
          <div class="element-wrapper">
            <h6 class="hed">
              Form submissions
            </h6>
            <!-- <a href="/home_layouts/new" class="mr-2 mb-2 btn btn-outline-primary add-community" role="button"><b class="text_center">+ ADD NEW LAYOUT </b></a> -->
            <div class="element-box">
              <div class="table-responsive full-width-tab">
                <table id="dataTable1" width="100%" class="table table-striped table-lightfont">
                  <thead>
                    <tr class="ss1">
                      <th>First name</th>
                      <th>Last name</th>
                      <th>Phone</th>
                      <th>Email</th>
                      <th>When are you planning to buy home</th>
                      <th>Additional info</th>
                      <th>Attachment</th>
                      <th>Show source url</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                   <% @form_submissions.each do |form_submission| %>
                      <tr>
                        <td data-link="<%= edit_form_submission_path(form_submission) %>", style='cursor: pointer'>
                          <%= form_submission.first_name %>      
                        </td>
                        <td data-link="<%= edit_form_submission_path(form_submission) %>", style='cursor: pointer'><%= form_submission.last_name %></td>
                        <td data-link="<%= edit_form_submission_path(form_submission) %>", style='cursor: pointer'><%= form_submission.phone %></td>
                        <td data-link="<%= edit_form_submission_path(form_submission) %>", style='cursor: pointer'><%= form_submission.email %></td>
                        <td data-link="<%= edit_form_submission_path(form_submission) %>", style='cursor: pointer'><%= form_submission.planning %></td>
                        <td data-link="<%= edit_form_submission_path(form_submission) %>", style='cursor: pointer'><%= form_submission.additional_info %></td>
                        <td data-link="<%= edit_form_submission_path(form_submission) %>", style='cursor: pointer'><%= form_submission.attachment %></td>
                        <td data-link="<%= edit_form_submission_path(form_submission) %>", style='cursor: pointer'><%= form_submission.source_url %></td>
                        
                        <td>
                          <div class="mr-2 mb-2 btn btn-link delte" data-target ="#myModal_<%= form_submission.id %>" data-toggle = "modal">Delete</div>
                        </td> 
                       <!--  <td><%#= link_to 'Edit', edit_community_path(community) %></td> -->
                      </tr>
                      <div class="modal fade" id="myModal_<%= form_submission.id %>" role="dialog">
                        <div class="modal-dialog modal-sm">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h4 class="modal-title">Delete this submission?</h4>
                              <button type="button" class="close close1" data-dismiss="modal">&times;</button>
                              
                            </div>
                            <div class="modal-body">
                              <p>Are you sure you want to delete <%= form_submission.first_name %> ? This is permanent and cannot be reversed.</p>
                            </div>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-default" data-dismiss="modal">CANCEL</button>
                              <%= link_to "DELETE", form_submission_path(form_submission.id) , method: :delete, class: "mr-2 mb-2 btn btn-danger"%>    
                            </div>
                          </div>
                        </div>
                      </div>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="display-type"></div>
</div>

<script type="text/javascript">
  $("td[data-link]").click(function() {
    window.location = $(this).data("link")
  })
</script>

app/views/form_submissions/new.html.erb
<div class="container">

  <%= form_for @form_submission do |f| %>
    <%= render partial: 'form', locals: {form_submission: @form_submission, f: f}%>
  <% end %>
</div>