config/routes.rb
Rails.application.routes.draw do
  resources :marketing_pages
  resources :events do
  	collection do
      post :update_event
  	end
  end
  resources :communities do
  	collection do
  		post :find_community
      get :find_phone
      get :find_email
      get :find_short_name
      get :dashboard
      post :update_crop
      post :universal_search
      get :featured_community
      get :count_for_home_and_community
  	end
  end
	get 'page_not_found', to: 'communities#page_not_found', as: :page_not_found
	post "communities/new_community" => "communities#new_community"
  resources :community_facilities
  root to: "admin/login#new"	
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 #get 'community_offers#new'
 get 'contacts/index'

 get 'contacts/show'
 #get 'community_offer', to: :new, controller: 'community_offers'
 # resources :contacts
 resources :home_for_sales do
  collection do
    post 'sales_force_callback'
    get :featured_home
    get :sorted_homes
  end
 end
 
 resources :home_layouts
 resources :form_submissions
 resources :community_offers
 resources :community_categories
 resources :pdf_info_packs do
    collection do
      put :featured_pdf_info_pack
      get :featured_pack
    end
  end
namespace :admin do 
 resources :login do
  post 'static_login', on: :collection
  get 'logout', on: :collection
 end
end  

 
end

app/models/activity.rb
class Activity < ApplicationRecord
  mount_uploader :image, ActivityImageUploader
  belongs_to :community, inverse_of: :activities
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/community.rb
class Community < ApplicationRecord
  include AlgoliaSearch

  has_and_belongs_to_many :community_categories,dependent: :destroy
  has_one :pdf_info_pack
  has_many :community_facilities, inverse_of: :community, dependent: :destroy
  has_one :community_offer
  # belongs_to :home_for_sale
  has_many :activities, inverse_of: :community,dependent: :destroy
  has_many :why_live_heres, inverse_of: :community,dependent: :destroy
  has_many :facebook_links, inverse_of: :community,dependent: :destroy
  has_many :community_images, inverse_of: :community, dependent: :destroy
  accepts_nested_attributes_for :community_facilities, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :activities, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :why_live_heres, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :facebook_links, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :community_images, reject_if: :all_blank, allow_destroy: true
  validates_presence_of :slug
  validates_presence_of :short_name
  validates_uniqueness_of :short_name, :slug
  # validates :community_icon, presence: true
  # validates :community_logo, presence: true
  # validates :salesperson_image, presence: true
  # validates :featured_image, presence: true
  after_create :update_slug
  before_update :assign_slug
  mount_uploader :community_logo, ImageUploader
  mount_uploader :community_icon, ImageUploader
  mount_uploader :community_infopack, AttachmentUploader
  mount_uploader :salesperson_image, ImageUploader
  mount_uploader :featured_image, ImageUploader   
  mount_uploader :masterplan_pdf, MasterplanUploader
  mount_uploader :masterplan_image, ImageUploader 
  mount_uploader :legend_image, ImageUploader 
  enum state_name: [
    "Queensland", "New South Wales", "Victoria"
  ]

  geocoded_by :street_address, :latitude => :latitude, :longitude => :longitude
  after_validation :geocode

  algoliasearch do
    # all attributes will be sent
  end
  
	def slug
    self.short_name.downcase.gsub(" ", "-")  
  end
  
  def to_param
    slug
  end
  private

  def assign_slug
    self.slug = self.short_name.downcase.gsub(" ", "-")
  end

  def update_slug
    update_attributes slug: assign_slug
  end
  
end

app/models/community_category.rb
class CommunityCategory < ApplicationRecord
	has_and_belongs_to_many :communities
	mount_uploader :image, ImageUploader
end

app/models/community_facility.rb
class CommunityFacility < ApplicationRecord
  mount_uploader :image, FacilityImageUploader
  belongs_to :community, inverse_of: :community_facilities
end

app/models/community_image.rb
class CommunityImage < ApplicationRecord
	mount_uploader :community_images, WhyLiveHereImageUploader
  belongs_to :community, inverse_of: :community_images
  validates :community_images, presence: true
end

app/models/community_offer.rb
class CommunityOffer < ApplicationRecord
	validates :title, presence: true
	#validates :image, presence: true
	mount_uploader :image, ImageUploader
	has_many :communities
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
  include AlgoliaSearch
  belongs_to :community, optional: true
	algoliasearch do
    # all attributes will be sent
  end
end

app/models/facebook_link.rb
class FacebookLink < ApplicationRecord
  belongs_to :community, inverse_of: :facebook_links
end

app/models/form_submission.rb
class FormSubmission < ApplicationRecord
end

app/models/home_for_sale.rb
class HomeForSale < ApplicationRecord
	include AlgoliaSearch
  
  belongs_to :community, optional: true
	algoliasearch do
    # all attributes will be sent
  end

  def upload_on_cloudinary
  	new_images = []
  	self.images.each do |img|
  	  url = Cloudinary::Uploader.upload(img)
  	  new_images << url["secure_url"]
  	end
  	self.images = new_images
  	self.save!
  end
end

app/models/home_layout.rb
class HomeLayout < ApplicationRecord
	mount_uploader :floorplan_image, LayoutUploader
	mount_uploader :floorplan_pdf, FloorplanUploader
	validates :feature_title1, presence: true
	validates :feature_title2, presence: true
	validates :feature_title3, presence: true
	validates :feature_title4, presence: true
	validates :description1, presence: true
	validates :description2, presence: true
	validates :description3, presence: true
	validates :description4, presence: true
end

app/models/marketing_page.rb
class MarketingPage < ApplicationRecord
end

app/models/pdf_info_pack.rb
class PdfInfoPack < ApplicationRecord
  has_many :communities
  mount_uploader :info_pdf, PdfinfoUploader
  validates_size_of :info_pdf, maximum: 20.megabytes, message: "should be less than 20 MB"
end

app/models/why_live_here.rb
class WhyLiveHere < ApplicationRecord
  #validates :image, presence: true
  mount_uploader :image, WhyLiveHereImageUploader
  belongs_to :community, inverse_of: :why_live_heres
end

app/controllers/community_offers_controller.rb
class CommunityOffersController < ApplicationController

	before_action :authenticate_user, unless: :json_request?
	skip_before_action :verify_authenticity_token


	def new
		@community_offer = CommunityOffer.new
	end

	def create
		@community_offer = CommunityOffer.new(community_offer_params)
		if params[:publish_submit]
      @community_offer.publish = true
    else
       @community_offer.publish = false 
	  end
		if @community_offer.save!
		  respond_to do |format|
		  	flash[:info] = 'Offer Created'
	      format.html {redirect_to community_offers_path}
	      format.js
	    end
	  end  
	end


	def show
    @community_offer = CommunityOffer.find(params[:id])
  end

	def index
    @community_offer = CommunityOffer.all
  end


  def edit
    @community_offer = CommunityOffer.find(params[:id])
  end

  def update
	  @community_offer = CommunityOffer.find(params[:id])
	  if @community_offer.update(community_offer_params)
	  	flash[:info] = 'Offer Updated'
	    redirect_to community_offers_path
	  else
	    render 'edit'
	  end
  end

  def destroy
  	@community_offer = CommunityOffer.find_by_id(params[:id])
  	if @community_offer.communities.present?
      flash[:info] = 'Offer can not be deleted. As it is assigned to community'
    else
	    @community_offer.destroy!
	    flash[:info] = 'Offer deleted'
    end
    redirect_to community_offers_path
  end

  def authenticate_user
  	unless session[:user_email].present?
  		redirect_to root_path
  	end
  end 

	private
	  def community_offer_params
	    params.require(:community_offer).permit(:title, :description, :more_about, :image, :publish)
	  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/community_offers_helper.rb
module CommunityOffersHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_layouts_helper.rb
module HomeLayoutsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/community_offers/_form.html.erb
<div class="all-wrapper menu-side">
  <div class="layout-w">
    <div class="menu-mobile menu-activated-on-click color-scheme-dark">
    </div>
    <div class="content-w">
      <ul class="breadcrumb">
        <% if @community_offer.new_record? %>
          <li class="breadcrumb-item">
            <a href="#">Home</a>
          </li>
          <li class="breadcrumb-item">
            <a href="/community_offers">Offers</a>
          </li>
          <li class="breadcrumb-item">
            <a href="#">New offer</a>
          </li>
        <% else %>
          <li class="breadcrumb-item">
            <a href="#">Home</a>
          </li>
          <li class="breadcrumb-item">
            <a href="/community_offers">Offers</a>
          </li>
          <li class="breadcrumb-item">
            <a href="#">Edit offer</a>
          </li>
        <% end %>  
      </ul>
      <div class="content-i">
        <div class="content-box"><div class="row">
<div class="col-lg-12">
<div class="element-wrapper">
  <div class="element-box">
    <% if @community_offer.new_record? %>
      <div class="form-group">
        <p class="addnewcomm">New offer</p>
      </div>
    <% else %>
      <div class="form-group">
        <p class="addnewcomm">Edit offer</p>
      </div>
    <% end %> 
      <div class="form-group">
        <label for="" class="short-name">Offer title*</label>
        <%= f.text_field :title, class: "form-control which-part-will-be-c", required: true, placeholder: "Add title here" %>
      </div>
      <div class="form-group">
        <label for="" class="enter-a-community-na"> Description*</label>
        <%= f.text_area :description, class: "form-control", placeholder: "Start entering the description", required: true, rows: "3", cols: "50" %>
      </div>
       <div class="form-group">
        <label for="" class="enter-a-community-na"> Offer link*</label>
        <%= f.text_field :more_about, class: "form-control which-part-will-be-c", placeholder: "Enter offer link here", required: true %>
      </div>
     <div class="col-sm-6">
      <div class="form-group">
        <label for="" class="enter-a-community-na">Offer Image*</label>
        <%-if @community_offer.image? %>
          <div id="uploaded_image">
            <%= cl_image_tag(@community_offer.image_url.sub! 'upload', 'upload/w_800,h_400,c_fill') %>
          </div>
          </br>
          <input id="upload_widget_opener7" required="required" accept="image/png" type="button" name="community_offer[image]" aria-required="true" value="upload">
        <%-else %>
          <div id="uploaded_image">
          </div>
          <%= f.file_field :image, class: "pdffile", id: "upload_widget_opener7", style: "visibility:hidden;" %>
        <% end %>
        <p class="min-width-450-px-in-a">Min. 526px height by 690px width</p>
        <div class="help-block form-text with-errors form-control-feedback"></div>
      </div>
      </div>
     <!--  <div class="form-group">
        <#% if @community_offer.new_record? %>
        <%#= f.hidden_field(:publish) %>
      <#% else %>
        <%#= f.label(:publish) %>
        <%#= f.check_box(:publish) %>
      <#% end %>  -->
      <!-- </div>   -->
      <% if @community_offer.new_record? %>
        <div class="form-buttons-w">
          <%= f.submit :"SAVE", class: "mr-2 mb-2 btn btn-success draft1" , name: "publish_submit"%>
        </div>
      <% else %>
        <%= f.submit :"SAVE", class: "mr-2 mb-2 btn btn-succ update" %>
        <%= link_to "DELETE", community_offer_path(community_offer.id) , method: :delete, class: "mr-2 mb-2 btn btn-dan update1" %>
      <% end %>   
  </div>
</div>
</div>
</div>
        </div>
      </div>
    </div>
  </div>
</div>

<script> 
  $( document ).ready(function() {
    $("#new_community_offer").validate({
      errorElement: 'span',
      errorClass: 'desc',
      rules: {
        "community_offer_title": {
         required: true
        },

        "community_offer_description": {
         required: true
        },
        "community_offer_more_about": {
         required: true
        },
        "community_offer_image": {
          required: true,
          accept:"png",
          width: 900,
          height: 686
        }
      }    
    });  
  });
</script>
<script src="//widget.cloudinary.com/global/all.js" type="text/javascript"></script>  
<script type="text/javascript">  
  $('#upload_widget_opener7').cloudinary_upload_widget(
    { cloud_name: 'gateway-lifestyle', upload_preset: 'ecaya9l1', 
      cropping: 'server', folder: 'user_photos',
      cropping_show_dimensions: "true",
      theme: "white",
      min_image_width: '690',
      min_image_height: '526',
      client_allowed_formats: ['jpg', 'png'], 
      gravity: "custom",
      moderation: "webpurify",cropping_default_selection_ratio: '1.0',
      multiple: false },
      function(error, result) { 
        if(error == null){
          $("#uploaded_image").html('<img src="'+result[0]["thumbnail_url"]+'">')
        }
      });
</script>
<script type="text/javascript">
  $('#new_community_offer').on('submit',function(){
    var logo = $('#upload_widget_opener7');
    if(logo.val() == "" ){
      alert("Please upload image.");
      return false;
    }
  })
</script>

app/views/community_offers/edit.html.erb
<div class="container">
  <% if @community_offer.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@community_offer.errors.count, "error") %> prohibited
        this community from being saved:
      </h2>
      <ul>
        <% @community_offer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_for @community_offer do |f| %>
    <%= render partial: 'form', locals: {community_offer: @community_offer, f: f}%>
  <% end %>
</div>

 

app/views/community_offers/index.html.erb
<div class="all-wrapper menu-side">
  <div class="layout-w">
    <div class="content-w">
      <ul class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="#">Home</a>
        </li>
        <li class="breadcrumb-item">
          <a href="/community_offers/new">Offers</a>
        </li>
      </ul>
      <div class="content-i">
        <div class="content-box">
          <div class="element-wrapper">
            <span class="hed">Offers</span>
            <a href="/community_offers/new" class="mr-2 mb-2 btn btn-outline-primary add-community" role="button">+ ADD NEW OFFER</a>
            <div class="element-box box">
              <div class="table-responsive">
                <table id="dataTable1" width="100%" class="table table-striped table-lightfont">
                  <thead>
                    <tr class="ss1">
                      <th>Image</th>  
                      <th>Offer Title</th>
                      <th>Description</th>
                      <th>Link</th>
                      <!-- <th>Visibility</th> -->
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                   <% @community_offer.each do |community_offer| %>
                      <tr>
                        <td data-link="<%= edit_community_offer_path(community_offer) %>", style='cursor: pointer'>
                          <% if community_offer.image.present? %>
                            <%= cl_image_tag(community_offer.image_url.to_s , :size => "160x80", :crop => :fill) %>
                          <% end %>      
                        </td>
                        <td data-link="<%= edit_community_offer_path(community_offer) %>", style='cursor: pointer'><%= community_offer.title.truncate(50) %></td>
                        <td data-link="<%= edit_community_offer_path(community_offer) %>", style='cursor: pointer'><%= community_offer.description.truncate(50) %></td>
                        <td data-link="<%= edit_community_offer_path(community_offer) %>", style='cursor: pointer'><%= community_offer.more_about.truncate(50) %></td>
                        <!-- <td data-link="<%= edit_community_offer_path(community_offer) %>", style='cursor: pointer'><#% if community_offer.publish %>    true
                        <#% else %>
                          false
                        <#% end %>  
                        </td> -->
                        <td>
                          <!-- <div class="mr-2 mb-2 btn btn-link" onclick="$('#myModal').modal('show');">Delete</div> -->
                          <div class="mr-2 mb-2 btn btn-link delte" data-target ="#myModal_<%= community_offer.id %>" data-toggle = "modal">Delete</div>

                        </td> 
                       <!--  <td><%#= link_to 'Edit', edit_community_path(community) %></td> -->
                      </tr>
                      <div class="modal fade" id="myModal_<%= community_offer.id %>" role="dialog">
                        <div class="modal-dialog modal-sm">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h4 class="modal-title">Delete this offer?</h4>
                              <button type="button" class="close close1" data-dismiss="modal">&times;</button>
                              
                            </div>
                            <div class="modal-body">
                              <p>Are you sure you want to delete <%= community_offer.title %> ? This is permanent and cannot be reversed.</p>
                            </div>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-default1" data-dismiss="modal">CANCEL</button> 
                              <%= link_to "DELETE", community_offer_path(community_offer.id) , method: :delete, class: "mr-2 mb-2 btn btn-danger"%>     
                            </div>
                          </div>
                        </div>
                      </div>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="display-type"></div>
</div>

<script type="text/javascript">
  $("td[data-link]").click(function() {
    window.location = $(this).data("link")
  })
</script>

app/views/community_offers/new.html.erb
<div class="container">
  <% if @community_offer.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@community_offer.errors.count, "error") %> prohibited
        this community_offer from being saved:
      </h2>
      <ul>
        <% @community_offer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_for @community_offer do |f| %>
    <%= render partial: 'form', locals: {community_offer: @community_offer, f: f}%>
  <% end %>
</div>