config/routes.rb
Rails.application.routes.draw do
  resources :marketing_pages
  resources :events do
  	collection do
      post :update_event
  	end
  end
  resources :communities do
  	collection do
  		post :find_community
      get :find_phone
      get :find_email
      get :find_short_name
      get :dashboard
      post :update_crop
      post :universal_search
      get :featured_community
      get :count_for_home_and_community
  	end
  end
	get 'page_not_found', to: 'communities#page_not_found', as: :page_not_found
	post "communities/new_community" => "communities#new_community"
  resources :community_facilities
  root to: "admin/login#new"	
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 #get 'community_offers#new'
 get 'contacts/index'

 get 'contacts/show'
 #get 'community_offer', to: :new, controller: 'community_offers'
 # resources :contacts
 resources :home_for_sales do
  collection do
    post 'sales_force_callback'
    get :featured_home
    get :sorted_homes
  end
 end
 
 resources :home_layouts
 resources :form_submissions
 resources :community_offers
 resources :community_categories
 resources :pdf_info_packs do
    collection do
      put :featured_pdf_info_pack
      get :featured_pack
    end
  end
namespace :admin do 
 resources :login do
  post 'static_login', on: :collection
  get 'logout', on: :collection
 end
end  

 
end

app/models/marketing_page.rb
class MarketingPage < ApplicationRecord
end

app/controllers/marketing_pages_controller.rb
class MarketingPagesController < ApplicationController
  before_action :set_marketing_page, only: [:show, :edit, :update, :destroy]

  # GET /marketing_pages
  # GET /marketing_pages.json
  def index
    @marketing_pages = MarketingPage.all
  end

  # GET /marketing_pages/1
  # GET /marketing_pages/1.json
  def show
  end

  # GET /marketing_pages/new
  def new
    @marketing_page = MarketingPage.new
  end

  # GET /marketing_pages/1/edit
  def edit
  end

  # POST /marketing_pages
  # POST /marketing_pages.json
  def create
    @marketing_page = MarketingPage.new(marketing_page_params)

    respond_to do |format|
      if @marketing_page.save
        format.html { redirect_to marketing_pages_path, notice: 'Marketing page was successfully created.' }
        format.json { render :show, status: :created, location: @marketing_page }
      else
        format.html { render :new }
        format.json { render json: @marketing_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marketing_pages/1
  # PATCH/PUT /marketing_pages/1.json
  def update
    respond_to do |format|
      if @marketing_page.update(marketing_page_params)
        format.html { redirect_to marketing_pages_path, notice: 'Marketing page was successfully updated.' }
        format.json { render :show, status: :ok, location: @marketing_page }
      else
        format.html { render :edit }
        format.json { render json: @marketing_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marketing_pages/1
  # DELETE /marketing_pages/1.json
  def destroy
    @marketing_page.destroy
    respond_to do |format|
      format.html { redirect_to marketing_pages_url, notice: 'Marketing page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marketing_page
      @marketing_page = MarketingPage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def marketing_page_params
      params.require(:marketing_page).permit(:title, :slug, :content, :meta_tag, :seo_title, :meta_description)
    end
end

app/helpers/marketing_pages_helper.rb
module MarketingPagesHelper
end

app/views/marketing_pages/_form.html.erb
<div class="all-wrapper menu-side">
  <div class="layout-w">
    <div class="menu-mobile menu-activated-on-click color-scheme-dark">
    </div>
    <div class="content-w">
      <ul class="breadcrumb">
        <% if @marketing_page.new_record? %>
          <li class="breadcrumb-item">
            <a href="#">Home</a>
          </li>
          <li class="breadcrumb-item">
            <a href="/marketing_pages">Marketing pages</a>
          </li>
          <li class="breadcrumb-item">
            <a href="#">New marketing page</a>
          </li>
        <% else %>
          <li class="breadcrumb-item">
            <a href="#">Home</a>
          </li>
          <li class="breadcrumb-item">
            <a href="/marketing_pages">Marketing pages</a>
          </li>
          <li class="breadcrumb-item">
            <a href="#">Edit marketing pages</a>
          </li>
        <% end %>  
      </ul>
      <div class="content-i">
        <div class="content-box"><div class="row">
<div class="col-lg-12">
<div class="element-wrapper">
  <div class="element-box">
    <% if @marketing_page.new_record? %>
      <div class="form-group">
        <p class="addnewcomm">New marketing page</p>
      </div> 
    <% else %>
      <div class="form-group">
        <p class="addnewcomm">Edit marketing page</p>
      </div>
    <% end %>    
      <div class="form-group">
        <label for="" class="enter-a-community-na">Title</label>
        <%= f.text_field :title, class: "form-control which-part-will-be-c", placeholder: "Page title", required: true %>
      </div>

      <div class="form-group">
        <label for="" class="enter-a-community-na">Slug/url</label>
        <% if @marketing_page.new_record? %>
        <%= f.text_field :slug, class: "form-control which-part-will-be-c", placeholder: "Page url", required: true %>
      <% else %>
        <%= f.text_field :slug, class: "form-control which-part-will-be-c", placeholder: "Page url", required: true, disabled: true  %>
      <% end %> 
      </div>

      <div class="form-group">
        <label for="" class="enter-a-community-na">Content</label>
        <%= f.text_area :content, class: "form-control which-part-will-be-c", placeholder: "Page content", required: true %>
      </div>

      <div class="form-group">
        <label for="" class="enter-a-community-na">SEO Title</label>
        <%= f.text_field :seo_title, class: "form-control which-part-will-be-c", placeholder: "Seo title", required: true %>
      </div>

      <div class="form-group">
        <label for="" class="enter-a-community-na">Meta Description</label>
        <%= f.text_area :meta_description, class: "form-control which-part-will-be-c", placeholder: "Write about here of meta description", required: true %>
      </div>
      <% if @marketing_page.new_record? %>
        <div class="form-buttons-w">
          <%= f.submit :"SAVE", class: "mr-2 mb-2 btn btn-success draft1" %>
        </div>
      <% else %>
        <%#= f.submit :"UPDATE", class: "button-background" %>
        <%= f.submit :"SAVE", class: "mr-2 mb-2 btn btn-succ update" %>
        <%= link_to "DELETE", marketing_page_path(marketing_page.id) , method: :delete, class: "mr-2 mb-2 btn btn-dan update1"%>
      <% end %>   
  </div>
</div>
</div>
</div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/marketing_pages/edit.html.erb
<div class="container">
  <% if @marketing_page.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@marketing_page.errors.count, "error") %> prohibited
        this page from being saved:
      </h2>
      <ul>
        <% @marketing_page.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_for @marketing_page do |f| %>
    <%= render partial: 'form', locals: {marketing_page: @marketing_page, f: f}%>
  <% end %>
</div>

app/views/marketing_pages/index.html.erb
<div class="all-wrapper menu-side">
  <div class="layout-w">
    <div class="content-w">
      <ul class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="#">Home</a>
        </li>
        <li class="breadcrumb-item">
          <a href="/marketing_pages/new">Marketing pages</a>
        </li>
      </ul>
      <div class="content-i">
        <div class="content-box">
          <div class="element-wrapper">
            <span class="hed">Marketing pages</span>
            <a href="/marketing_pages/new" class="mr-2 mb-2 btn btn-outline-primary add-community" role="button">+ ADD NEW PAGES</a>
            <div class="element-box box">
              <div class="table-responsive full-width-tab">
                <table id="dataTable1" width="100%" class="table table-striped table-lightfont">
                  <thead>
                    <tr class="ss1">
                      <th>Title</th>
                      <th>Slug</th>
                      <th>Content</th>
                      <th>SEO Title</th>
                      <th>Meta Description</th>
                      <th>Action</th>
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                   <% @marketing_pages.each do |marketing_page| %>
                      <tr>
                        <td data-link="<%= edit_marketing_page_path(marketing_page) %>", style='cursor: pointer'>
                          <%= marketing_page.title %>      
                        </td>
                        <td data-link="<%= edit_marketing_page_path(marketing_page) %>", style='cursor: pointer'>
                          <%= marketing_page.slug %>      
                        </td>
                        <td data-link="<%= edit_marketing_page_path(marketing_page) %>", style='cursor: pointer'>
                          <%= marketing_page.content %>      
                        </td>
                        <td data-link="<%= edit_marketing_page_path(marketing_page) %>", style='cursor: pointer'>
                          <%= marketing_page.seo_title %>      
                        </td>
                         <td data-link="<%= edit_marketing_page_path(marketing_page) %>", style='cursor: pointer'>
                          <%= marketing_page.meta_description %>      
                        </td>
                        <td>
                          <div class="mr-2 mb-2 btn btn-link delte" data-target ="#myModal_<%= marketing_page.id %>" data-toggle = "modal">Delete</div>
                        </td> 
                       <td><%= link_to 'Show', marketing_page_path(marketing_page) ,class: "mr-2 mb-2 btn btn-link delte" %></td>
                      </tr>
                      <div class="modal fade" id="myModal_<%= marketing_page.id %>" role="dialog">
                        <div class="modal-dialog modal-sm">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h4 class="modal-title">Delete this page?</h4>
                              <button type="button" class="close close1" data-dismiss="modal">&times;</button>
                              
                            </div>
                            <div class="modal-body">
                              <p>Are you sure you want to delete <%= marketing_page.title %> ? This is permanent and cannot be reversed.</p>
                            </div>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-default1" data-dismiss="modal">CANCEL</button>
                              <%= link_to "DELETE", marketing_page_path(marketing_page.id) , method: :delete, class: "mr-2 mb-2 btn btn-danger"%>    
                            </div>
                          </div>
                        </div>
                      </div>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="display-type"></div>
</div>

<script type="text/javascript">
  $("td[data-link]").click(function() {
    window.location = $(this).data("link")
  })
</script>

app/views/marketing_pages/new.html.erb
<div class="container">

  <%= form_for @marketing_page do |f| %>
    <%= render partial: 'form', locals: {marketing_page: @marketing_page, f: f}%>
  <% end %>
</div>

app/views/marketing_pages/show.html.erb
<div class="all-wrapper menu-side">
  <div class="layout-w">
    <div class="content-w">
      <div class="content-i">
        <div class="content-box">
          <div class="element-wrapper">
            <h6>
              Marketing Page
            </h6>
      <p>
        <strong class="info">Title:</strong>
        <%= @marketing_page.title %>
      </p>

      <p>
        <strong class="info">Slug:</strong>
        <%= @marketing_page.slug %>
      </p>

      <p>
        <strong class="info">Content:</strong>
        <%= @marketing_page.content %>
      </p>

      <p>
        <strong class="info">SEO Title:</strong>
        <%= @marketing_page.seo_title %>
      </p>

      <p>
        <strong class="info">Meta Description:</strong>
        <%= @marketing_page.meta_description %>
      </p>
       <%= link_to 'Edit', edit_marketing_page_path(@marketing_page), class: 'btn btn-primary' %> 
       <%= link_to 'Back', marketing_pages_path, class: 'btn btn-primary'%>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>