config/routes.rb
Rails.application.routes.draw do
  resources :marketing_pages
  resources :events do
  	collection do
      post :update_event
  	end
  end
  resources :communities do
  	collection do
  		post :find_community
      get :find_phone
      get :find_email
      get :find_short_name
      get :dashboard
      post :update_crop
      post :universal_search
      get :featured_community
      get :count_for_home_and_community
  	end
  end
	get 'page_not_found', to: 'communities#page_not_found', as: :page_not_found
	post "communities/new_community" => "communities#new_community"
  resources :community_facilities
  root to: "admin/login#new"	
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 #get 'community_offers#new'
 get 'contacts/index'

 get 'contacts/show'
 #get 'community_offer', to: :new, controller: 'community_offers'
 # resources :contacts
 resources :home_for_sales do
  collection do
    post 'sales_force_callback'
    get :featured_home
    get :sorted_homes
  end
 end
 
 resources :home_layouts
 resources :form_submissions
 resources :community_offers
 resources :community_categories
 resources :pdf_info_packs do
    collection do
      put :featured_pdf_info_pack
      get :featured_pack
    end
  end
namespace :admin do 
 resources :login do
  post 'static_login', on: :collection
  get 'logout', on: :collection
 end
end  

 
end

app/models/activity.rb
class Activity < ApplicationRecord
  mount_uploader :image, ActivityImageUploader
  belongs_to :community, inverse_of: :activities
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/community.rb
class Community < ApplicationRecord
  include AlgoliaSearch

  has_and_belongs_to_many :community_categories,dependent: :destroy
  has_one :pdf_info_pack
  has_many :community_facilities, inverse_of: :community, dependent: :destroy
  has_one :community_offer
  # belongs_to :home_for_sale
  has_many :activities, inverse_of: :community,dependent: :destroy
  has_many :why_live_heres, inverse_of: :community,dependent: :destroy
  has_many :facebook_links, inverse_of: :community,dependent: :destroy
  has_many :community_images, inverse_of: :community, dependent: :destroy
  accepts_nested_attributes_for :community_facilities, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :activities, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :why_live_heres, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :facebook_links, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :community_images, reject_if: :all_blank, allow_destroy: true
  validates_presence_of :slug
  validates_presence_of :short_name
  validates_uniqueness_of :short_name, :slug
  # validates :community_icon, presence: true
  # validates :community_logo, presence: true
  # validates :salesperson_image, presence: true
  # validates :featured_image, presence: true
  after_create :update_slug
  before_update :assign_slug
  mount_uploader :community_logo, ImageUploader
  mount_uploader :community_icon, ImageUploader
  mount_uploader :community_infopack, AttachmentUploader
  mount_uploader :salesperson_image, ImageUploader
  mount_uploader :featured_image, ImageUploader   
  mount_uploader :masterplan_pdf, MasterplanUploader
  mount_uploader :masterplan_image, ImageUploader 
  mount_uploader :legend_image, ImageUploader 
  enum state_name: [
    "Queensland", "New South Wales", "Victoria"
  ]

  geocoded_by :street_address, :latitude => :latitude, :longitude => :longitude
  after_validation :geocode

  algoliasearch do
    # all attributes will be sent
  end
  
	def slug
    self.short_name.downcase.gsub(" ", "-")  
  end
  
  def to_param
    slug
  end
  private

  def assign_slug
    self.slug = self.short_name.downcase.gsub(" ", "-")
  end

  def update_slug
    update_attributes slug: assign_slug
  end
  
end

app/models/community_category.rb
class CommunityCategory < ApplicationRecord
	has_and_belongs_to_many :communities
	mount_uploader :image, ImageUploader
end

app/models/community_facility.rb
class CommunityFacility < ApplicationRecord
  mount_uploader :image, FacilityImageUploader
  belongs_to :community, inverse_of: :community_facilities
end

app/models/community_image.rb
class CommunityImage < ApplicationRecord
	mount_uploader :community_images, WhyLiveHereImageUploader
  belongs_to :community, inverse_of: :community_images
  validates :community_images, presence: true
end

app/models/community_offer.rb
class CommunityOffer < ApplicationRecord
	validates :title, presence: true
	#validates :image, presence: true
	mount_uploader :image, ImageUploader
	has_many :communities
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
  include AlgoliaSearch
  belongs_to :community, optional: true
	algoliasearch do
    # all attributes will be sent
  end
end

app/models/facebook_link.rb
class FacebookLink < ApplicationRecord
  belongs_to :community, inverse_of: :facebook_links
end

app/models/form_submission.rb
class FormSubmission < ApplicationRecord
end

app/models/home_for_sale.rb
class HomeForSale < ApplicationRecord
	include AlgoliaSearch
  
  belongs_to :community, optional: true
	algoliasearch do
    # all attributes will be sent
  end

  def upload_on_cloudinary
  	new_images = []
  	self.images.each do |img|
  	  url = Cloudinary::Uploader.upload(img)
  	  new_images << url["secure_url"]
  	end
  	self.images = new_images
  	self.save!
  end
end

app/models/home_layout.rb
class HomeLayout < ApplicationRecord
	mount_uploader :floorplan_image, LayoutUploader
	mount_uploader :floorplan_pdf, FloorplanUploader
	validates :feature_title1, presence: true
	validates :feature_title2, presence: true
	validates :feature_title3, presence: true
	validates :feature_title4, presence: true
	validates :description1, presence: true
	validates :description2, presence: true
	validates :description3, presence: true
	validates :description4, presence: true
end

app/models/marketing_page.rb
class MarketingPage < ApplicationRecord
end

app/models/pdf_info_pack.rb
class PdfInfoPack < ApplicationRecord
  has_many :communities
  mount_uploader :info_pdf, PdfinfoUploader
  validates_size_of :info_pdf, maximum: 20.megabytes, message: "should be less than 20 MB"
end

app/models/why_live_here.rb
class WhyLiveHere < ApplicationRecord
  #validates :image, presence: true
  mount_uploader :image, WhyLiveHereImageUploader
  belongs_to :community, inverse_of: :why_live_heres
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_flash_message.html.erb
<% flash.delete(:timedout).each do |k, message| %>
  <div class="alert alert-dismissable" id="successMessage">
    <button class="close" data-dismiss="alert" type="button">
      <span>&times;</span>
      <span class="sr-only">Close</span>
    </button>
    <%= raw(message) %>
  </div>
<% end %>
<script type="text/javascript">
	$(document).ready(function(){
    setTimeout(function() {
      $('#successMessage').fadeOut('fast');
    }, 5000); // <-- time in milliseconds
  });
</script>

app/views/layouts/_menu_side.html.erb
<div class="desktop-menu menu-side-w menu-activated-on-click">
  <div class="logo-w">
    <img src="/assets/logo.svg" style="height: 56.97px; width: 144px;">
  </div>
  <div class="menu-and-user">
    <div class="logged-user-w">
      <div class="logged-user-i">
        <div class="logged-user-info-w">
          <div class="logged-user-name username">
            Gateway Admin
          </div>
          <p class="adminis">ADMINISTRATOR</p>
        </div>
        <div class="logged-user-menu">
          <div class="logged-user-avatar-info">
            <div class="avatar-w">
              <img alt="" src="/assets/logo.svg" style="height: 56.97px; width: 144px;">
            </div>
            <div class="logged-user-info-w">
              <div class="logged-user-name">
                Admin
              </div>
            </div>
          </div>
          <div class="bg-icon">
            <i class="os-icon os-icon-wallet-loaded"></i>
          </div>
          <ul>
            <li>
              <%=link_to "Logout", logout_admin_login_index_path, class: "os-icon os-icon-signs-11"%>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <ul class="main-menu">
      <li class=<%= params[:controller] == "communities" ? 'active_link' : ''%>>
        <a href="/communities">
          <div class="icon-w">
            <div class="os-icon os-icon-window-content"></div>
          </div>
          <span>Communities</span></a>
      </li>
      <li class=<%= params[:controller] == "home_for_sales" ? 'active_link' : ''%>>
        <a href="/home_for_sales">
          <div class="icon-w">
            <div class="os-icon os-icon-window-content"></div>
          </div>
          <span class="homesale">Homes for sale</span></a>
      </li>

      <li class=<%= params[:controller] == "community_offers" ? 'active_link' : ''%>>
        <a href="/community_offers">
          <div class="icon-w">
            <div class="os-icon os-icon-window-content"></div>
          </div>
          <span class="events">Offers</span></a>
      </li>
      <li class=<%= params[:controller] == "community_categories" ? 'active_link' : ''%>>
        <a href="/community_categories">
          <div class="icon-w">
            <div class="os-icon os-icon-window-content"></div>
          </div>
          <span class="events">Categories</span></a>
      </li>
      <li class=<%= params[:controller] == "pdf_info_packs" ? 'active_link' : ''%>>
        <a href="/pdf_info_packs">
          <div class="icon-w">
            <div class="os-icon os-icon-window-content"></div>
          </div>
          <span class="events">Pdf Info Packs</span></a>
      </li>


      <li class=<%= params[:controller] == "events" ? 'active_link' : ''%>>
        <a href="/events">
          <div class="icon-w">
            <div class="os-icon os-icon-window-content"></div>
          </div>
          <span class="events">Events</span></a>
      </li>
      <li class=<%= params[:controller] == "home_layouts" ? 'active_link' : ''%>>
        <a href="/home_layouts">
          <div class="icon-w">
            <div class="os-icon os-icon-window-content"></div>
          </div>
          <span class="events">Home Layouts</span></a>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/_mobile_menu.html.erb
<div class="menu-mobile menu-activated-on-click color-scheme-dark">
  <div class="mm-logo-buttons-w">
    <a class="mm-logo" href="index.html"><img src="/assets/logo.png"><span>Clean Admin</span></a>
    <div class="mm-buttons">
      <div class="content-panel-open">
        <div class="os-icon os-icon-grid-circles"></div>
      </div>
      <div class="mobile-menu-trigger">
        <div class="os-icon os-icon-hamburger-menu-1"></div>
      </div>
    </div>
  </div>
  <div class="menu-and-user">
    <div class="logged-user-w">
      <div class="avatar-w">
        <img alt="" src="/assets/avatar1.jpg">
      </div>
      <div class="logged-user-info-w">
        <div class="logged-user-name">
          Maria Gomez
        </div>
        <div class="logged-user-role">
          Administrator
        </div>
      </div>
    </div>
    <ul class="main-menu">
      <li class="has-sub-menu">
        <a href="index.html">
          <div class="icon-w">
            <div class="os-icon os-icon-window-content"></div>
          </div>
          <span>Dashboard</span></a>
        <ul class="sub-menu">
          <li>
            <a href="index.html">Dashboard 1</a>
          </li>
          <li>
            <a href="apps_projects.html">Dashboard 2</a>
          </li>
          <li>
            <a href="layouts_menu_top_image.html">Dashboard 3</a>
          </li>
        </ul>
      </li>
      <li class="has-sub-menu">
        <a href="#">
          <div class="icon-w">
            <div class="os-icon os-icon-hierarchy-structure-2"></div>
          </div>
          <span>Menu Styles</span></a>
        <ul class="sub-menu">
          <li>
            <a href="layouts_menu_side.html">Side Menu Light</a>
          </li>
          <li>
            <a href="layouts_menu_side_dark.html">Side Menu Dark</a>
          </li>
          <li>
            <a href="apps_pipeline.html">Side &amp; Top Dark <strong class="badge badge-danger">New</strong></a>
          </li>
          <li>
            <a href="apps_projects.html">Side &amp; Top <strong class="badge badge-danger">New</strong></a>
          </li>
          <li>
            <a href="layouts_menu_side_compact.html">Compact Side Menu</a>
          </li>
          <li>
            <a href="layouts_menu_side_compact_dark.html">Compact Menu Dark</a>
          </li>
          <li>
            <a href="layouts_menu_top.html">Top Menu Light</a>
          </li>
          <li>
            <a href="layouts_menu_top_dark.html">Top Menu Dark</a>
          </li>
          <li>
            <a href="layouts_menu_top_image.html">Top Menu Image</a>
          </li>
        </ul>
      </li>
      <li class="has-sub-menu">
        <a href="#">
          <div class="icon-w">
            <div class="os-icon os-icon-delivery-box-2"></div>
          </div>
          <span>Applications</span></a>
        <ul class="sub-menu">
          <li>
            <a href="apps_email.html">Email Application</a>
          </li>
          <li>
            <a href="apps_projects.html">Projects List</a>
          </li>
          <li>
            <a href="apps_full_chat.html">Chat Application</a>
          </li>
          <li>
            <a href="apps_todo.html">To Do Application <strong class="badge badge-danger">New</strong></a>
          </li>
          <li>
            <a href="misc_chat.html">Popup Chat</a>
          </li>
          <li>
            <a href="apps_pipeline.html">CRM Pipeline <strong class="badge badge-danger">New</strong></a>
          </li>
          <li>
            <a href="rentals_index_grid.html">Property Listing <strong class="badge badge-danger">New</strong></a>
          </li>
          <li>
            <a href="misc_calendar.html">Calendar</a>
          </li>
        </ul>
      </li>
      <li class="has-sub-menu">
        <a href="#">
          <div class="icon-w">
            <div class="os-icon os-icon-newspaper"></div>
          </div>
          <span>Pages</span></a>
        <ul class="sub-menu">
          <li>
            <a href="misc_invoice.html">Invoice</a>
          </li>
          <li>
            <a href="rentals_index_grid.html">Property Listing <strong class="badge badge-danger">New</strong></a>
          </li>
          <li>
            <a href="misc_charts.html">Charts</a>
          </li>
          <li>
            <a href="front_home.html">Front Site <strong class="badge badge-danger">New</strong></a>
          </li>
          <li>
            <a href="auth_login.html">Login</a>
          </li>
          <li>
            <a href="auth_register.html">Register</a>
          </li>
          <li>
            <a href="auth_lock.html">Lock Screen</a>
          </li>
          <li>
            <a href="misc_pricing_plans.html">Pricing Plans</a>
          </li>
          <li>
            <a href="misc_error_404.html">Error 404</a>
          </li>
          <li>
            <a href="misc_error_500.html">Error 500</a>
          </li>
        </ul>
      </li>
      <li class="has-sub-menu">
        <a href="#">
          <div class="icon-w">
            <div class="os-icon os-icon-pencil-12"></div>
          </div>
          <span>UI Kit</span></a>
        <ul class="sub-menu">
          <li>
            <a href="uikit_modals.html">Modals</a>
          </li>
          <li>
            <a href="uikit_alerts.html">Alerts</a>
          </li>
          <li>
            <a href="uikit_grid.html">Grid</a>
          </li>
          <li>
            <a href="uikit_progress.html">Progress</a>
          </li>
          <li>
            <a href="uikit_popovers.html">Popover</a>
          </li>
          <li>
            <a href="uikit_tooltips.html">Tooltips</a>
          </li>
          <li>
            <a href="uikit_buttons.html">Buttons</a>
          </li>
          <li>
            <a href="uikit_dropdowns.html">Dropdowns</a>
          </li>
          <li>
            <a href="uikit_typography.html">Typography</a>
          </li>
        </ul>
      </li>
      <li class="has-sub-menu">
        <a href="#">
          <div class="icon-w">
            <div class="os-icon os-icon-user-male-circle"></div>
          </div>
          <span>Users</span></a>
        <ul class="sub-menu">
          <li>
            <a href="users_profile_big.html">Big Profile</a>
          </li>
          <li>
            <a href="users_profile_small.html">Compact Profile</a>
          </li>
        </ul>
      </li>
      <li class="has-sub-menu">
        <a href="#">
          <div class="icon-w">
            <div class="os-icon os-icon-tasks-checked"></div>
          </div>
          <span>Forms</span></a>
        <ul class="sub-menu">
          <li>
            <a href="forms_regular.html">Regular Forms</a>
          </li>
          <li>
            <a href="forms_validation.html">Form Validation</a>
          </li>
          <li>
            <a href="forms_wizard.html">Form Wizard</a>
          </li>
          <li>
            <a href="forms_uploads.html">File Uploads</a>
          </li>
          <li>
            <a href="forms_wisiwig.html">Wisiwig Editor</a>
          </li>
        </ul>
      </li>
      <li class="has-sub-menu">
        <a href="#">
          <div class="icon-w">
            <div class="os-icon os-icon-grid-squares"></div>
          </div>
          <span>Tables</span></a>
        <ul class="sub-menu">
          <li>
            <a href="tables_regular.html">Regular Tables</a>
          </li>
          <li>
            <a href="tables_datatables.html">Data Tables</a>
          </li>
          <li>
            <a href="tables_editable.html">Editable Tables</a>
          </li>
        </ul>
      </li>
      <li class="has-sub-menu">
        <a href="#">
          <div class="icon-w">
            <div class="os-icon os-icon-robot-1"></div>
          </div>
          <span>Icons</span></a>
        <ul class="sub-menu">
          <li>
            <a href="icon_fonts_simple_line_icons.html">Simple Line Icons</a>
          </li>
          <li>
            <a href="icon_fonts_themefy.html">Themefy Icons</a>
          </li>
          <li>
            <a href="icon_fonts_picons_thin.html">Picons Thin</a>
          </li>
          <li>
            <a href="icon_fonts_dripicons.html">Dripicons</a>
          </li>
          <li>
            <a href="icon_fonts_eightyshades.html">Eightyshades</a>
          </li>
          <li>
            <a href="icon_fonts_entypo.html">Entypo</a>
          </li>
          <li>
            <a href="icon_fonts_font_awesome.html">Font Awesome</a>
          </li>
          <li>
            <a href="icon_fonts_foundation_icon_font.html">Foundation Icon Font</a>
          </li>
          <li>
            <a href="icon_fonts_metrize_icons.html">Metrize Icons</a>
          </li>
          <li>
            <a href="icon_fonts_picons_social.html">Picons Social</a>
          </li>
          <li>
            <a href="icon_fonts_batch_icons.html">Batch Icons</a>
          </li>
          <li>
            <a href="icon_fonts_dashicons.html">Dashicons</a>
          </li>
          <li>
            <a href="icon_fonts_typicons.html">Typicons</a>
          </li>
          <li>
            <a href="icon_fonts_weather_icons.html">Weather Icons</a>
          </li>
          <li>
            <a href="icon_fonts_light_admin.html">Light Admin</a>
          </li>
        </ul>
      </li>
    </ul>
    <div class="mobile-menu-magic">
      <h4>
        Light Admin
      </h4>
      <p>
        Clean Bootstrap 4 Template
      </p>
      <div class="btn-w">
        <a class="btn btn-white btn-rounded" href="https://themeforest.net/item/light-admin-clean-bootstrap-dashboard-html-template/19760124?ref=Osetin" target="_blank">Purchase Now</a>
      </div>
    </div>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GatewayLifestyle</title>
    <meta charset="utf-8">
    <meta content="ie=edge" http-equiv="x-ua-compatible">
    <meta content="template language" name="keywords">
    <meta content="Tamerlan Soziev" name="author">
    <meta content="Admin dashboard html template" name="description">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <link href="/assets/favicon1.png" rel="shortcut icon">
    <link href="apple-touch-icon.png" rel="apple-touch-icon">
    <link href="https://fonts.googleapis.com/css?family=Rubik:300,400,500" rel="stylesheet" type="text/css">

    <%= stylesheet_link_tag 'admin', media: 'all' %>
    <%= javascript_include_tag 'admin' %>
   <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
    
    ga('create', 'UA-XXXXXXXX-X', 'auto');
    ga('send', 'pageview');
   </script>
    <%= csrf_meta_tags %>
  </head>
  <body>
    
    <div class="all-wrapper menu-side with-side-panel">
      <div class="layout-w">
        <%= render partial: "layouts/mobile_menu" %>
        <%= render partial: "layouts/menu_side" %>

        <div class="content-w">
          <%= render partial: "layouts/flash_message" %>
          <%= yield %>
        </div>
      </div>
      <div class="display-type"></div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GatewayLifestyle</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= cloudinary_js_config %>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.js"></script>
    <script src="https://widget.cloudinary.com/global/all.js" type="text/javascript"></script> 
    <script src="http://jqueryvalidation.org/files/dist/jquery.validate.min.js"></script>
    <script src="http://jqueryvalidation.org/files/dist/additional-methods.min.js"></script>
  </head>

  <body>
    <header>
    <%=render 'layouts/header/header'%>
    </header>
    <main>
   <!--  <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
     <% #flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <%# end %> -->
    <div class="notifications-alerts">
      <%= render partial: "layouts/flash_message" %>
    </div>  
    <%= yield %>
    </main>
    <%=render 'layouts/footer/footer'%>
  </body>
</html>

app/views/layouts/header/_default.html.erb
<nav class="navbar navbar-expand-md navbar-inverse navbar-custom">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-md-0">
      <!-- <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li> -->
       <% if session[:user_email].present? %>
          <li class="nav-item">
           <%=link_to "Communities", communities_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
           <%=link_to "Home for sale", '#', class: "nav-link"%>
          </li>
          <li class="nav-item">
           <%=link_to "Events",'#', class: "nav-link"%>
          </li>
          <li class="nav-item">
           <%=link_to "Offers",new_community_offer_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
           <%=link_to "PDF info packs", '#', class: "nav-link"%>
          </li>
          <li class="nav-item">
           <%=link_to "Categories", '#', class: "nav-link"%>
          </li>
      <%else%>
        <li class="nav-item">
           <%=link_to "Admin login" %>
        </li>
      <%end%>
    </ul>
    <% if session[:user_email].present? %>
      <form class="form-inline my-2 my-lg-0">
        <%=link_to "Admin logout", logout_admin_login_index_path, class: "nav-link"%>
      </form>
    <%end%>
  </div>
</nav>

app/views/layouts/header/_header.html.erb
 <%=render 'layouts/header/default'%>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GatewayLifestyle</title>
    <meta charset="utf-8">
    <meta content="ie=edge" http-equiv="x-ua-compatible">
    <meta content="template language" name="keywords">
    <meta content="Tamerlan Soziev" name="author">
    <meta content="Admin dashboard html template" name="description">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <link href="/assets/favicon1.png" rel="shortcut icon">
    <link href="apple-touch-icon.png" rel="apple-touch-icon">
    <link href="https://fonts.googleapis.com/css?family=Rubik:300,400,500" rel="stylesheet" type="text/css">

    <%= stylesheet_link_tag 'admin', media: 'all' %>
    
    <%= csrf_meta_tags %>
  </head>
  <body class="auth-wrapper">
    <div class="all-wrapper menu-side with-pattern">
      <%= yield %>
    </div>
  </body>
</html>